#!/bin/sh

as_skill_sourced=0
if [ -n "${ZSH_VERSION:-}" ]; then
    case "$ZSH_EVAL_CONTEXT" in
        *:file) as_skill_sourced=1 ;;
    esac
elif [ -n "${BASH_VERSION:-}" ]; then
    (return 0 2>/dev/null) && as_skill_sourced=1
else
    case "$0" in
        *install.sh) as_skill_sourced=0 ;;
        *) as_skill_sourced=1 ;;
    esac
fi

if [ ! -d domains ] || [ ! -d core/skills ]; then
    echo "install.sh: запустите из корня claude-harness (не нашёл domains/ и core/skills/ здесь)" >&2
    return 1 2>/dev/null || exit 1
fi

if ! command -v go >/dev/null 2>&1; then
    echo "install.sh: нужен go, не найден в PATH — https://go.dev/dl/ (на macOS: brew install go)" >&2
    return 1 2>/dev/null || exit 1
fi

echo "Собираю as-skill..."
if ! go build -o as-skill ./tools; then
    echo "install.sh: сборка не удалась" >&2
    return 1 2>/dev/null || exit 1
fi

as_skill_root="$(pwd)"
case ":$PATH:" in
    *":$as_skill_root:"*) ;;
    *) export PATH="$as_skill_root:$PATH" ;;
esac

as_skill_shquote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

as_skill_guard_begin="# >>> as-skill >>>"
as_skill_guard_end="# <<< as-skill <<<"
# shellcheck disable=SC2016
as_skill_guard_line='[ -f "$HOME/.config/as-skill/env" ] && . "$HOME/.config/as-skill/env"'
as_skill_rc_summary=""

as_skill_ensure_guard() {
    if [ ! -f "$1" ]; then
        if ! touch "$1" 2>/dev/null; then
            echo "install.sh: не удалось создать $1 — пропускаю" >&2
            return 1
        fi
    fi
    if grep -qF "$as_skill_guard_begin" "$1" 2>/dev/null; then
        as_skill_rc_summary="$as_skill_rc_summary $1"
        return 0
    fi
    if ! {
        printf '\n%s\n' "$as_skill_guard_begin"
        printf '%s\n' "$as_skill_guard_line"
        printf '%s\n' "$as_skill_guard_end"
    } >> "$1" 2>/dev/null; then
        echo "install.sh: не удалось дописать $1 — пропускаю" >&2
        return 1
    fi
    as_skill_rc_summary="$as_skill_rc_summary $1"
    return 0
}

as_skill_persisted=0
as_skill_config_dir="$HOME/.config/as-skill"
as_skill_env_file="$as_skill_config_dir/env"

if [ -z "$HOME" ]; then
    echo "install.sh: \$HOME не задан — PATH не будет сохранён для новых терминалов" >&2
elif ! mkdir -p "$as_skill_config_dir" 2>/dev/null; then
    echo "install.sh: не удалось создать $as_skill_config_dir — PATH не будет сохранён для новых терминалов" >&2
else
    as_skill_old_root=""
    if [ -f "$as_skill_env_file" ]; then
        as_skill_old_root=$(sed -n 's/^# as-skill-root: //p' "$as_skill_env_file" 2>/dev/null | head -n 1)
    fi
    as_skill_quoted_root=$(as_skill_shquote "$as_skill_root")
    if {
        printf '%s\n' "# Managed by as-skill install.sh -- safe to delete, regenerated by the next: source install.sh"
        printf '%s\n' "# as-skill-root: $as_skill_root"
        printf '%s\n' "export PATH=$as_skill_quoted_root:\"\$PATH\""
    } > "$as_skill_env_file" 2>/dev/null; then
        as_skill_persisted=1
        if [ -n "$as_skill_old_root" ] && [ "$as_skill_old_root" != "$as_skill_root" ]; then
            echo "as-skill PATH entry updated: $as_skill_old_root → $as_skill_root"
        fi
    else
        echo "install.sh: не удалось записать $as_skill_env_file — PATH не будет сохранён для новых терминалов" >&2
    fi
    unset as_skill_old_root as_skill_quoted_root
fi

as_skill_fish_shell=0
if [ -n "$HOME" ]; then
    case "$SHELL" in
        */zsh)
            as_skill_ensure_guard "$HOME/.zshrc"
            ;;
        */bash)
            as_skill_ensure_guard "$HOME/.bash_profile"
            as_skill_ensure_guard "$HOME/.bashrc"
            ;;
        */fish)
            as_skill_fish_shell=1
            ;;
        *)
            as_skill_ensure_guard "$HOME/.profile"
            ;;
    esac
fi

if [ "$as_skill_sourced" = 1 ]; then
    echo "Готово: as-skill доступен в этой оболочке ($(command -v as-skill))."
    if [ "$as_skill_persisted" = 1 ]; then
        echo "PATH сохранён для новых терминалов: $as_skill_env_file"
        if [ -n "$as_skill_rc_summary" ]; then
            echo "  hook добавлен в:$as_skill_rc_summary"
            echo "Уже открытые другие терминалы нужно обновить ещё одним source install.sh (или открыть новый — дальше подхватится само)."
        elif [ "$as_skill_fish_shell" != 1 ]; then
            echo "  не удалось добавить hook ни в один rc-файл — новые терминалы PATH не подхватят, см. предупреждения выше." >&2
        fi
    fi
    if [ "$as_skill_fish_shell" = 1 ]; then
        echo "fish не поддерживается source install.sh напрямую для автообновления PATH — добавьте вручную: fish_add_path $as_skill_root"
    fi
    echo
    as-skill list domains
else
    echo "Собрано: ./as-skill"
    echo "Это дочерний процесс — PATH не может передаться в родительскую оболочку."
    echo "Чтобы as-skill сразу заработал в ЭТОЙ оболочке — запустите: source install.sh"
    if [ "$as_skill_persisted" = 1 ] && [ -n "$as_skill_rc_summary" ]; then
        echo "Для НОВЫХ терминалов PATH уже сохранён (hook в:$as_skill_rc_summary) — сработает само, без source install.sh."
    fi
    if [ "$as_skill_fish_shell" = 1 ]; then
        echo "fish не поддерживается source install.sh напрямую — добавьте вручную: fish_add_path $as_skill_root"
    fi
fi

unset as_skill_sourced as_skill_root
unset as_skill_persisted as_skill_config_dir as_skill_env_file as_skill_fish_shell
unset as_skill_rc_summary as_skill_guard_begin as_skill_guard_end as_skill_guard_line
unset -f as_skill_shquote as_skill_ensure_guard 2>/dev/null
